// Code generated by "stringer -type=ALPN -linecomment"; DO NOT EDIT.

package alpn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Multiplexer-1]
	_ = x[HTTP-2]
	_ = x[Raw-3]
}

const _ALPN_name = "multiplexerhttp/1.1raw"

var _ALPN_index = [...]uint8{0, 0, 11, 19, 22}

func (i ALPN) String() string {
	if i < 0 || i >= ALPN(len(_ALPN_index)-1) {
		return "ALPN(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ALPN_name[_ALPN_index[i]:_ALPN_index[i+1]]
}
