// Code generated by "stringer -type=Protocol -linecomment"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Yamux-1]
	_ = x[Mplex-2]
	_ = x[QUIC-3]
}

const _Protocol_name = "unknownyamuxmplexquic"

var _Protocol_index = [...]uint8{0, 7, 12, 17, 21}

func (i Protocol) String() string {
	if i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
