name: Pipeline
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build_17:
    name: Build Most Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}

      - name: Build linux/amd64
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-client-linux-amd64 ./cmd/client
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-server-linux-amd64 ./cmd/server

      - name: Build linux/arm64
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-client-linux-arm64 ./cmd/client
          CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-server-linux-arm64 ./cmd/server

      - name: Build windows/amd64
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-client-windows-amd64.exe ./cmd/client
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-server-windows-amd64.exe ./cmd/server

      - name: Build windows/arm64
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          CGO_ENABLED=0 GOARCH=arm64 GOOS=windows go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-client-windows-arm64.exe ./cmd/client
          CGO_ENABLED=0 GOARCH=arm64 GOOS=windows go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-server-windows-arm64.exe ./cmd/server

      - name: Build darwin/amd64
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-client-darwin-amd64 ./cmd/client
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-server-darwin-amd64 ./cmd/server
          
      - name: Build darwin/arm64
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          CGO_ENABLED=0 GOARCH=arm64 GOOS=darwin go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-client-darwin-arm64 ./cmd/client
          CGO_ENABLED=0 GOARCH=arm64 GOOS=darwin go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-server-darwin-arm64 ./cmd/server

      - name: Build illumos/amd64
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=illumos go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-client-illumos-amd64 ./cmd/client
          CGO_ENABLED=0 GOARCH=amd64 GOOS=illumos go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-server-illumos-amd64 ./cmd/server


      - name: Release Binaries
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/**
            example.config.yaml
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_16:
    name: Build Other Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.8

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}

      - name: Build android/arm64 Client w/ DNS Fix
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++ CGO_ENABLED=1 GOARCH=arm64 GOOS=android go build -tags 'osusergo netgo' -ldflags "-X 'main.Version=$BUILD_VERSION' -s -w -extldflags -static" -a -o bin/t-client-android-arm64 ./cmd/client


      - name: Release Binaries
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/**
            example.config.yaml
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
