name: Pipeline
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.6

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build linux/amd64
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-client-linux-amd64 ./cmd/client
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-server-linux-amd64 ./cmd/server
      - name: Build linux/arm64
        run: |
          CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-client-linux-arm64 ./cmd/client
          CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-server-linux-arm64 ./cmd/server
      - name: Build windows/amd64
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-client-windows-amd64.exe ./cmd/client
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-server-windows-amd64.exe ./cmd/server
      - name: Build darwin/amd64
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-client-darwin-amd64 ./cmd/client
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-server-darwin-amd64 ./cmd/server
      - name: Build darwin/arm64
        run: |
          CGO_ENABLED=0 GOARCH=arm64 GOOS=darwin go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-client-darwin-arm64 ./cmd/client
          CGO_ENABLED=0 GOARCH=arm64 GOOS=darwin go build -tags 'osusergo netgo' -ldflags '-s -w -extldflags "-static"' -a -o bin/t-server-darwin-arm64 ./cmd/server

      - name: Release Binaries
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/**
            config.example.yaml
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
